feat: worker displaying in section show
NetaM-OSC/NetAM pull request #136
Opened 2020-11-18 09:20 UTC by vfricou

Close #135

2020-11-18 09:21 UTC, sebastiendeu commented
<!--
  0 Errors
  1 Warning: There're changes, but no chang...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There're changes, but no changelog.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-18 09:25 UTC, sebastiendeu requested changes

2020-11-18 09:25 UTC, sebastiendeu commented on app/views/sections/show.html.haml
> +            = '%{name}' % { name: @section.worker_name }
```suggestion
            = @section.worker_name
```

2020-11-18 09:25 UTC, sebastiendeu commented on app/views/sections/show.html.haml
> +            = '%{timestamp}' % { timestamp: Time.at(last_scan) }
```suggestion
            = Time.at(last_scan)
```

2020-11-19 20:25 UTC, vfricou commented on app/views/sections/show.html.haml
> +            = '%{name}' % { name: @section.worker_name }
Fixed in latest commit

2020-11-19 20:26 UTC, vfricou commented on app/views/sections/show.html.haml
> +            = '%{timestamp}' % { timestamp: Time.at(last_scan) }
Fixed in latest commit

2020-11-19 20:52 UTC, sebastiendeu approved these changes

2020-11-19 20:54 UTC, merged