Feat/tools devices list
NetaM-OSC/NetAM pull request #150
Opened 2020-11-21 22:26 UTC by vfricou

Close #149

2020-11-21 22:26 UTC, sebastiendeu commented
<!--
  0 Errors
  1 Warning: There're changes, but no chang...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There're changes, but no changelog.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-12-01 08:48 UTC, sebastiendeu requested changes
Globaly:
- missing `netam.pot` update: `rake gettext:regenerate`
- missing API endpoints
- missing permission matrix on edit pages

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/device_types_controller.rb
> +    @device_types = DeviceType.all.filter { |vlan| can? :read, vlan }
Prefer usage of `Model.accessible_by(current_ability)` of [cancancan gem](https://github.com/CanCanCommunity/cancancan#fetching-records)

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/device_types_controller.rb
> +      redirect_to device_types_path, notice: 'Device type was successfully created.'
missing translation

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/device_types_controller.rb
> +      redirect_to device_types_path, notice: 'Device type was successfully updated.'
missing translation

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/device_types_controller.rb
> +    redirect_to device_types_url, notice: 'Device type was successfully destroyed.'
missing translation

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/devices_controller.rb
> +    @devices = Device.all
Missing accessibility filter

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/devices_controller.rb
> +      redirect_to devices_path, notice: 'Device was successfully created.'
missing translation

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/devices_controller.rb
> +      redirect_to devices_path, notice: 'Device was successfully updated.'
missing translation

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/devices_controller.rb
> +    redirect_to devices_url, notice: 'Device was successfully destroyed.'
missing translation

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/usages_controller.rb
> +        device_created = Device.create!(name: @usage.fqdn, device_type_id: 1)
`device_type_id: 1` ?

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/usages_controller.rb
> +        @usage.update!(device_id: device_created.id)
When your link is defined between usage ans device you can compact like this:
```suggestion
        @usage.update!(device: Device.create!(name: @usage.fqdn, device_type_id: 1))
```

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/usages_controller.rb
> +      end
same as line 45

2020-12-01 08:48 UTC, sebastiendeu commented on app/controllers/usages_controller.rb
> +    @usage.device.delete if @usage.device.present? && @usage.device.id == @usage.device_id
prefer cascading deletion in model

2020-12-01 08:48 UTC, sebastiendeu commented on app/models/usage.rb
> +  #
why ?

2020-12-01 08:48 UTC, sebastiendeu commented on app/views/device_types/_form.html.haml
> += form_with(model: @device_type, local: true) do |form|
here you should use `device` instead of `@device_type`

2020-12-01 08:48 UTC, sebastiendeu commented on db/migrate/20201121214655_create_devices.rb
> +      t.integer :p_size, null: true
`h_size` and `p_size` are too generalist

2020-12-01 08:48 UTC, sebastiendeu commented on app/views/devices/index.html.haml
> +          - if device.device_type_id.present?
prefer check on `device.device_type`

2020-12-02 13:28 UTC, vfricou commented on app/controllers/device_types_controller.rb
> +      redirect_to device_types_path, notice: 'Device type was successfully created.'
Fixed in next commit

2020-12-02 13:28 UTC, vfricou commented on app/controllers/device_types_controller.rb
> +      redirect_to device_types_path, notice: 'Device type was successfully updated.'
Fixed in next commit

2020-12-02 13:28 UTC, vfricou commented on app/controllers/device_types_controller.rb
> +    redirect_to device_types_url, notice: 'Device type was successfully destroyed.'
Fixed in next commit

2020-12-02 13:29 UTC, vfricou commented on app/controllers/devices_controller.rb
> +      redirect_to devices_path, notice: 'Device was successfully created.'
Fixed in next commit

2020-12-02 13:29 UTC, vfricou commented on app/controllers/devices_controller.rb
> +      redirect_to devices_path, notice: 'Device was successfully updated.'
Fixed in next commit

2020-12-02 13:29 UTC, vfricou commented on app/controllers/devices_controller.rb
> +    redirect_to devices_url, notice: 'Device was successfully destroyed.'
Fixed in next commit

2020-12-02 13:29 UTC, vfricou commented on app/controllers/usages_controller.rb
> +        @usage.update!(device_id: device_created.id)
Fixed in next commit

2020-12-02 13:29 UTC, vfricou commented on app/controllers/usages_controller.rb
> +      end
Fixed in next commit

2020-12-02 13:30 UTC, vfricou commented on app/models/usage.rb
> +  #
Because XD Just u fail, Fixed in next commit

2020-12-02 13:30 UTC, vfricou commented on app/views/devices/index.html.haml
> +          - if device.device_type_id.present?
Fixed in next commit

2020-12-04 08:29 UTC, vfricou commented on app/views/device_types/_form.html.haml
> += form_with(model: @device_type, local: true) do |form|
This is specific form for devices_type not for devices, the form not manage device.
So, I don't understand this change request.

2020-12-04 08:29 UTC, vfricou commented on db/migrate/20201121214655_create_devices.rb
> +      t.integer :p_size, null: true
Give mode details please ?

2020-12-04 08:35 UTC, sebastiendeu commented on app/views/device_types/_form.html.haml
> += form_with(model: @device_type, local: true) do |form|
On edit/new template you use this render instruction: `render 'form', device: @device_types`.
This instruction provide a variable `device` with the content of `@device_types`.
To reduce complexity you must use the variable enter in render params instead of instance variable

2020-12-04 08:41 UTC, vfricou commented on app/views/device_types/_form.html.haml
> += form_with(model: @device_type, local: true) do |form|
Ok, thanks for explanations. 

Fixed.

2020-12-04 08:42 UTC, vfricou commented on app/controllers/usages_controller.rb
> +        device_created = Device.create!(name: @usage.fqdn, device_type_id: 1)
Is fixed to 1 (default type provided into database migration) because is mandatory to create device.

2020-12-04 09:04 UTC, vfricou commented on app/controllers/device_types_controller.rb
> +    @device_types = DeviceType.all.filter { |vlan| can? :read, vlan }
Fixed in next commit

2020-12-04 09:05 UTC, vfricou commented on app/controllers/devices_controller.rb
> +    @devices = Device.all
Fixed in next commit

2020-12-04 09:19 UTC, sebastiendeu commented on db/migrate/20201121214655_create_devices.rb
> +      t.integer :p_size, null: true
To query `h_size` and `p_size` we use:
`Device.h_size` and `Device.p_size` but these keys are not clear.

Exemple:
`Device.rack_size` or `Device.rack_unit` and `Device.rack_depth` are clearer on what kind of value is returned by database.

2020-12-04 10:10 UTC, vfricou commented on db/migrate/20201121214655_create_devices.rb
> +      t.integer :p_size, null: true
Fixed in next commit

2020-12-04 13:07 UTC, vfricou commented on app/controllers/usages_controller.rb
> +    @usage.device.delete if @usage.device.present? && @usage.device.id == @usage.device_id
Fixed ahead

2020-12-04 16:32 UTC, sebastiendeu requested changes
On DeviceType:
- block delete in model with:
```
before_destroy do |dt|
  throw(:abort) if dt.name == 'None'
end
```

2020-12-04 16:32 UTC, sebastiendeu commented on config/routes.rb
> +    resources :device_types
missing except
```suggestion
    resources :devices, except: [:show]
    resources :device_types, except: [:show]
```

2020-12-04 16:41 UTC, sebastiendeu approved these changes

2020-12-04 16:46 UTC, merged