WIP feat: add tools whois
NetaM-OSC/NetAM pull request #351
Opened 2021-03-26 10:16 UTC by Rigonkmalk

2021-04-06 17:23 UTC, sebastiendeu requested changes

2021-04-06 17:23 UTC, sebastiendeu commented on app/models/whois.rb
> +  validates :domain, presence: true
Why you have created a model ?

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois.property_any_supported? :nameservers
You can use last condition to reduce code verbosity

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois
You have already condition on @whois

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois.property_any_supported? :nameservers
You can use last condition to reduce code verbosity

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois.property_any_supported? :registrar
You can use last condition to reduce code verbosity

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois.property_any_supported? :registrar
You can use last condition to reduce code verbosity

2021-04-06 17:23 UTC, sebastiendeu commented on app/views/utils/whois.html.haml
> +      - if @whois.property_any_supported? :registrar
You can use last condition to reduce code verbosity

2021-04-08 06:25 UTC, vfricou approved these changes

2021-04-08 06:37 UTC, sebastiendeu approved these changes

2021-04-08 07:11 UTC, merged