WIP: feat: DNS resolver
NetaM-OSC/NetAM pull request #355
Opened 2021-03-27 11:22 UTC by vfricou

#344

2021-03-27 11:25 UTC, vfricou commented
TODO :
- UT
- POT file

2021-03-29 16:19 UTC, sebastiendeu commented on lib/netam/network/dns.rb
> +        end
You can optimize your case like this
```suggestion
        result = Resolv::DNS.open do |dns|
          records = dns.getresources(entry, "Resolv::DNS::Resource::IN::#{type}".constantize)
          case type
          when 'A', 'AAAA'
            records.empty? ? [] : records.map { |r| r.address.to_s }
          when 'CNAME', 'NS'
            records.empty? ? [] : records.map { |r| r.name.to_s }
          when 'MX'
            records.empty? ? [] : records.map { |r| "#{r.preference} #{r.exchange}" }
          when 'TXT'
            records.empty? ? [] : records.map(&:data)
          when 'SRV'
            records.empty? ? [] : records.map { |r| "Port : #{r.port}, Priority : #{r.priority}, Target : #{r.target}, Weight : #{r.weight}" }
          when 'SOA'
            records.empty? ? [] : records.map { |r| "Serial : #{r.serial}, Host : #{r.mname}, Maintainer : #{r.rname}" }
          else
            nil
          end
        end
```

2021-03-29 16:20 UTC, sebastiendeu requested changes

2021-03-29 16:20 UTC, sebastiendeu commented on lib/netam/network/dns.rb
> +        end
You can optimize your case like this:
```suggestion
        result = Resolv::DNS.open do |dns|
          records = dns.getresources(entry, "Resolv::DNS::Resource::IN::#{type}".constantize)
          case type
          when 'A', 'AAAA'
            records.empty? ? [] : records.map { |r| r.address.to_s }
          when 'CNAME', 'NS'
            records.empty? ? [] : records.map { |r| r.name.to_s }
          when 'MX'
            records.empty? ? [] : records.map { |r| "#{r.preference} #{r.exchange}" }
          when 'TXT'
            records.empty? ? [] : records.map(&:data)
          when 'SRV'
            records.empty? ? [] : records.map { |r| "Port : #{r.port}, Priority : #{r.priority}, Target : #{r.target}, Weight : #{r.weight}" }
          when 'SOA'
            records.empty? ? [] : records.map { |r| "Serial : #{r.serial}, Host : #{r.mname}, Maintainer : #{r.rname}" }
          else
            nil
          end
        end
```

2021-04-01 19:33 UTC, sebastiendeu approved these changes

2021-04-01 19:44 UTC, merged