add: repository issues templates
NetaM-OSC/NetAM pull request #89
Opened 2020-10-30 22:44 UTC by vfricou

Adding bug report and feature template

2020-10-30 22:45 UTC, sebastiendeu commented
<!--
  0 Errors
  1 Warning: There're changes, but no chang...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There're changes, but no changelog.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-10-30 23:19 UTC, Rigonkmalk submitted a review, later dismissed

2020-10-30 23:29 UTC, Rigonkmalk reviewed
Ok for me

2020-11-03 16:52 UTC, tsarti requested changes

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +You could report any issues into project GitHub issue tracker
```suggestion
You can report any issues into project GitHub issue tracker
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +You could contribute to code to implement new feature, existing features enhancement, optimizations, etc…
```suggestion
You can contribute to the code to implement new features, existing features enhancement, optimizations, etc…
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +interface and usage as much as possible simple for a non expert user.
```suggestion
The project is axed to be as much user friendly as possible, when you propose contribution think to keep
interface and usage as simple as possible for a non expert user.
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +Because we want to create the best and usefull possible product for our users, we have a set of guidelines which ensure that all contributions are acceptable.
```suggestion
Because we want to create the best and  most usefull possible product for our users, we have a set of guidelines which ensure that all contributions are acceptable.
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +* Go ahead and fork the project and make your changes.  We encourage pull requests to allow for review and discussion of code changes.
```suggestion
* Go ahead, fork the project and make your changes.  We encourage pull requests to allow reviews and discussion about code changes.
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +We are based on [Angular contribution guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-coding-rules) for the essentiels of commit keys :
```suggestion
We are based on [Angular contribution guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-coding-rules) for the essentials of commit keys :
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +- chore: Massive update from multiples files
```suggestion
- chore: Massive update for multiples files
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +For each pull request you would submit, you must add an unrealeased changelog for will be computed at the release to create a update Changelog file.
```suggestion
For each pull request you would submit, you must add an unrealeased changelog which will be computed during the release to create an updated Changelog file.
```

2020-11-03 16:52 UTC, tsarti commented on CONTRIBUTING.md
> +A binary exist in repository to easily create unreleased changelog file. To create this file you must launch following command :
```suggestion
A binary exists in repository to easily create unreleased changelog file. To create this file you must launch following command :
```

2020-11-03 17:56 UTC, tsarti approved these changes

2020-11-03 18:10 UTC, merged