feat: language selector
NetaM-OSC/NetAM pull request #90
Opened 2020-10-31 00:16 UTC by Rigonkmalk

2020-10-31 00:17 UTC, sebastiendeu commented
<!--
  0 Errors
  1 Warning: There're changes, but no chang...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There're changes, but no changelog.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-07 15:43 UTC, sebastiendeu commented
<!--
  0 Errors
  1 Warning: There're changes, but no chang...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">There're changes, but no changelog.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-07 15:56 UTC, sebastiendeu commented on changelog/unreleased/add-language-selector.yml
> +type: changed
```suggestion
type: added
```

2020-11-07 15:57 UTC, sebastiendeu commented on changelog/unreleased/add-language-selector.yml
> +title: Add language selector
```suggestion
title: Add language selector dropdown in navbar
```

2020-11-07 16:08 UTC, vfricou requested changes
French traductions issues :
- On section / vlan / usage edit buttun update section : « Modifier ce(tte) … »
- On usage en FR : Oublier -> Change to Relacher ou Libérer
- On section show Éteint : Change to inactif
- On section show : All top buttons aren't translated

All page /register/edit isn't translated 
Dark theme switch isn't functionnal

2020-11-07 17:52 UTC, vfricou submitted a review, later dismissed

2020-11-07 17:58 UTC, vfricou approved these changes

2020-11-07 18:02 UTC, merged